/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.asynclist;

public final class Res {

	public static final class id {
		public static final int section_title = 4;
		public static final int item_title = 5;
		public static final int list = 6;
		public static final int item_desc = 7;
		public static final int button_reload = 8;
		public static final int item_picture = 9;
	}

	public static final class image {
		public static final int ITEM_NO_PICTURE = 0;
	}

	public static final class layout {
		public static final int ASYNC_LIST_SCREEN = 1;
		public static final int SECTION = 2;
		public static final int ITEM = 3;
	}

}
