/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.contactexample;

public final class Res {

	public static final class id {
		public static final int pick_contact_item = 84;
		public static final int phone_number = 85;
		public static final int other_email = 86;
		public static final int button_delete_contact = 87;
		public static final int button_add_prefill_contact = 88;
		public static final int button_update_contact = 89;
		public static final int contact_manager_screen_list = 90;
		public static final int button_save_contact = 91;
		public static final int button_create_contact = 92;
		public static final int home_address = 93;
		public static final int button_edit_contact = 94;
		public static final int mobile_phone = 95;
		public static final int work_email = 96;
		public static final int show_contact_item = 97;
		public static final int edit_contact_item = 98;
		public static final int name = 99;
		public static final int add_contact_item = 100;
		public static final int contact_list = 101;
		public static final int website = 102;
		public static final int button_get_all_contacts = 103;
		public static final int other_address = 104;
		public static final int button_pick_contact = 105;
		public static final int item_title = 106;
		public static final int operation_result = 107;
		public static final int job = 108;
		public static final int button_contact_details = 109;
		public static final int important_date = 110;
		public static final int layout_start = 111;
		public static final int work_address = 112;
		public static final int button_add_contact = 113;
		public static final int email = 114;
		public static final int address = 115;
		public static final int company = 116;
		public static final int work_phone = 117;
		public static final int home_phone = 118;
		public static final int button_show_contact = 119;
		public static final int other_phone = 120;
		public static final int notes = 121;
		public static final int home_email = 122;
	}

	public static final class layout {
		public static final int SAVE_CONTACT_SCREEN = 71;
		public static final int CONTACT_DETAILS_SCREEN = 72;
		public static final int CONTACT_MANAGER_SCREEN = 73;
		public static final int DELETE_CONTACT_SCREEN = 74;
		public static final int ADD_CONTACT_SCREEN = 75;
		public static final int SHOW_CONTACT_SCREEN = 76;
		public static final int NOT_SUPPORTED_LAYOUT = 77;
		public static final int CONTACTS_LIST_SCREEN = 78;
		public static final int PICK_CONTACT_SCREEN = 79;
		public static final int EDIT_CONTACT_SCREEN = 80;
		public static final int CONTACT_EDITOR_SCREEN = 81;
		public static final int GET_ALL_CONTACTS_SCREEN = 82;
		public static final int LIST_ITEM_VIEW = 83;
	}

	public static final class string {
		public static final int MAIN_TITLE = 0;
		public static final int CONTACT_MANAGER_TITLE = 1;
		public static final int CONTACT_DATABASE_TITLE = 2;
		public static final int ADD_TITLE = 3;
		public static final int EDIT_TITLE = 4;
		public static final int PICK_TITLE = 5;
		public static final int SHOW_TITLE = 6;
		public static final int SAVE_TITLE = 7;
		public static final int GET_ALL_TITLE = 8;
		public static final int CONTACT_DETAILS_TITLE = 9;
		public static final int DELETE_TITLE = 10;
		public static final int PICK_CONTACT = 11;
		public static final int ADD_CONTACT = 12;
		public static final int ADD_CONTACT_PREF = 13;
		public static final int EDIT_CONTACT = 14;
		public static final int SHOW_CONTACT = 15;
		public static final int SAVE_CONTACT = 16;
		public static final int GET_ALL_CONTACTS = 17;
		public static final int DELETE_CONTACT = 18;
		public static final int OP_RESULT = 19;
		public static final int OP_RESULT_ERROR = 20;
		public static final int PRESS_ADD = 21;
		public static final int PRESS_ADD_PREF = 22;
		public static final int ADDED_CONTACT = 23;
		public static final int CONTACT = 24;
		public static final int PREF_NAME = 25;
		public static final int PREF_PHONE = 26;
		public static final int PREF_EMAIL = 27;
		public static final int PRESS_PICK_AND_EDIT = 28;
		public static final int EDIT_IT = 29;
		public static final int SAVE_IT = 30;
		public static final int PRESS_PICK = 31;
		public static final int PICKED_CONTACT = 32;
		public static final int PRESS_PICK_AND_SHOW = 33;
		public static final int SHOW_IT = 34;
		public static final int PRESS_SAVE = 35;
		public static final int UPDATE_JOHN_DOE = 36;
		public static final int UPDATE_CONTACT = 37;
		public static final int PRESS_GET_ALL = 38;
		public static final int PRESS_PICK_AND_DELETE = 39;
		public static final int DELETE_IT = 40;
		public static final int CONTACT_NAME = 41;
		public static final int CONTACT_PHONE = 42;
		public static final int CONTACT_MOBILE_PHONE = 43;
		public static final int CONTACT_HOME_PHONE = 44;
		public static final int CONTACT_WORK_PHONE = 45;
		public static final int CONTACT_OTHER_PHONE = 46;
		public static final int CONTACT_EMAIL = 47;
		public static final int CONTACT_HOME_EMAIL = 48;
		public static final int CONTACT_WORK_EMAIL = 49;
		public static final int CONTACT_OTHER_EMAIL = 50;
		public static final int CONTACT_MOBILE_EMAIL = 51;
		public static final int CONTACT_ADDRESS = 52;
		public static final int CONTACT_HOME_ADDRESS = 53;
		public static final int CONTACT_WORK_ADDRESS = 54;
		public static final int CONTACT_OTHER_ADDRESS = 55;
		public static final int CONTACT_JOB = 56;
		public static final int CONTACT_JOB_DEP = 57;
		public static final int CONTACT_COMPANY = 58;
		public static final int CONTACT_DATE = 59;
		public static final int CONTACT_DATE_BIRTHDAY = 60;
		public static final int CONTACT_DATE_ANNIVERSARY = 61;
		public static final int CONTACT_DATE_OTHER = 62;
		public static final int CONTACT_URL = 63;
		public static final int CONTACT_NOTES = 64;
		public static final int NEW_CONTACT_TITLE = 65;
		public static final int PICK_EXISTING = 66;
		public static final int CREATE_NEW = 67;
		public static final int CONTACTS_LIST_TITLE = 68;
		public static final int CONTACT_DETAILS = 69;
		public static final int TXT_NOT_SUPPORTED = 70;
	}

}
