/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.helloworld;

public final class Res {

	public static final class string {
		public static final int TXT_HELLO_WORLD = 0;
	}

}
