/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.conditionalcoding;

public final class Res {

	public static final class image {
		public static final int IMAGE_SUN = 2;
		public static final int IMAGE_MOON = 3;
	}

	public static final class string {
		public static final int TXT_HELLO_WORLD = 0;
		public static final int TXT_GOODBYE_WORLD = 1;
	}

}
