/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.serviceexample;

public final class Res {

	public static final class id {
		public static final int layout_start = 7;
		public static final int button_stop_services = 8;
		public static final int button_immediate = 9;
		public static final int button_schedule_minute = 10;
		public static final int button_schedule_30_minutes = 11;
	}

	public static final class image {
		public static final int NOTIF_ICON = 2;
		public static final int LAUNCH_IMG = 3;
		public static final int ACCESSORY_ICON = 4;
	}

	public static final class layout {
		public static final int NOT_SUPPORTED_LAYOUT = 5;
		public static final int SERVICE_SCREEN = 6;
	}

	public static final class music {
		public static final int SOUND_NOTIF = 1;
	}

	public static final class string {
		public static final int TXT_NOT_SUPPORTED = 0;
	}

}
