/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.jsonexample;

public final class Res {

	public static final class id {
		public static final int DISCUSSION_USER_NAME = 13;
		public static final int TL_WRITING_WITH_JSONWRITER_CONTENT = 14;
		public static final int BUTTON_READ_JSONREADER = 15;
		public static final int BUTTON_READ_JSONARRAY = 16;
		public static final int DISCUSSION_LAYOUT = 17;
		public static final int TL_JSON_STRING_TITLE = 18;
		public static final int TL_WRITING_WITH_JSONARRAY_CONTENT = 19;
		public static final int BUTTON_READ_JSON = 20;
		public static final int DISCUSSION_TEXT = 21;
		public static final int TEXT_LABEL_JSON_STRING = 22;
		public static final int BUTTON_WRITE_JSON = 23;
	}

	public static final class layout {
		public static final int MAIN_SCREEN = 8;
		public static final int DISCUSSION_ITEM = 9;
		public static final int READING_SCREEN = 10;
		public static final int WRITING_SCREEN = 11;
		public static final int DISCUSSION_SCREEN = 12;
	}

	public static final class string {
		public static final int JSON_STRING_TITLE = 0;
		public static final int JSON_STRING = 1;
		public static final int READ_JSON = 2;
		public static final int WRITE_JSON = 3;
		public static final int READ_JSONARRAY = 4;
		public static final int READ_JSONREADER = 5;
		public static final int WRITING_WITH_JSONARRAY = 6;
		public static final int WRITING_WITH_JSONWRITER = 7;
	}

}
