/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.locationexample;

public final class Res {

	public static final class id {
		public static final int ID_MIN_DISTANCE_RESULT = 41;
		public static final int ID_PROXIMITY_LATITUDE_RESULT = 42;
		public static final int ID_LOCATION_STATUS = 43;
		public static final int ID_BUTTON_START = 44;
		public static final int ID_COST_ALLOWED = 45;
		public static final int ID_TIMESTAMP_RESULT = 46;
		public static final int ID_TRACK_MY_LOCATION = 47;
		public static final int ID_LAST_KNOWN_LOCATION = 48;
		public static final int ID_BUTTON_CANCEL = 49;
		public static final int ID_SPEED_RESULT = 50;
		public static final int ID_PROXIMITY_RADIUS_RESULT = 51;
		public static final int layout_start = 52;
		public static final int ID_USE_DEFAULT_CRITERIA = 53;
		public static final int ID_BEARING_RESULT = 54;
		public static final int ID_MIN_DISTANCE = 55;
		public static final int ID_LONGITUDE = 56;
		public static final int ID_TIMESTAMP = 57;
		public static final int ID_MIN_TIME_RESULT = 58;
		public static final int ID_ALTITUDE_RESULT = 59;
		public static final int ID_BUTTON_ADD_REGION = 60;
		public static final int ID_PROXIMITY_LONGITUDE = 61;
		public static final int ID_ALTITUDE_REQUIRED = 62;
		public static final int ID_LONGITUDE_RESULT = 63;
		public static final int ID_ALTITUDE = 64;
		public static final int ID_REGION_LISTVIEW = 65;
		public static final int ID_LOCATE_ME = 66;
		public static final int ID_PROXIMITY_LONGITUDE_RESULT = 67;
		public static final int ID_MIN_TIME = 68;
		public static final int ID_BEARING = 69;
		public static final int ID_ACCURACY = 70;
		public static final int ID_PROXIMITY_LATITUDE = 71;
		public static final int ID_LISTVIEW = 72;
		public static final int ID_PROXIMITY = 73;
		public static final int ID_SPEED = 74;
		public static final int ID_BUTTON_MANAGE = 75;
		public static final int ID_ACCURACY_RESULT = 76;
		public static final int ID_BUTTON_SAVE = 77;
		public static final int ID_POWER_REQUIREMENT = 78;
		public static final int ID_POWER_REQUIREMENT_RESULT = 79;
		public static final int ID_BUTTON_STOP = 80;
		public static final int ID_LATITUDE_RESULT = 81;
		public static final int ID_DISTANCE_TO = 82;
		public static final int ID_LATITUDE = 83;
		public static final int ID_PROXIMITY_RADIUS = 84;
	}

	public static final class layout {
		public static final int CRITERIA_DETAILS_SCREEN = 34;
		public static final int PROXIMITY_REGION_DETAILS_SCREEN = 35;
		public static final int PROXIMITY_REGION_LIST_SCREEN = 36;
		public static final int MAIN_SCREEN = 37;
		public static final int NOT_SUPPORTED_LAYOUT = 38;
		public static final int PROXIMITY_SCREEN = 39;
		public static final int LOCATION_SCREEN = 40;
	}

	public static final class string {
		public static final int LOCATION_EXAMPLE = 0;
		public static final int SAVE = 1;
		public static final int PREFERENCES = 2;
		public static final int LOCATION_STATUS = 3;
		public static final int LOCATE_ME = 4;
		public static final int TRACK_MY_LOCATION = 5;
		public static final int LAST_KNOWN_LOCATION = 6;
		public static final int PROXIMITY = 7;
		public static final int DISTANCE_TO = 8;
		public static final int GEOCODER = 9;
		public static final int LATITUDE = 10;
		public static final int LONGITUDE = 11;
		public static final int ALTITUDE = 12;
		public static final int SPEED = 13;
		public static final int BEARING = 14;
		public static final int TIMESTAMP = 15;
		public static final int START = 16;
		public static final int STOP = 17;
		public static final int DEFAULT = 18;
		public static final int ACCURACY = 19;
		public static final int MIN_TIME = 20;
		public static final int MIN_DISTANCE = 21;
		public static final int POWER_REQUIREMENT = 22;
		public static final int COST_ALLOWED = 23;
		public static final int ALTITUDE_REQUIRED = 24;
		public static final int RADIUS = 25;
		public static final int MANAGE = 26;
		public static final int ADD = 27;
		public static final int MONITORED_REGIONS = 28;
		public static final int EDIT = 29;
		public static final int CANCEL = 30;
		public static final int DELETE = 31;
		public static final int TXT_NOT_SUPPORTED = 32;
		public static final int LOCATION_DISABLED_BY_USER = 33;
	}

}
