/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.specific;

public final class Res {

	public static final class string {
		public static final int TXT_HELLO = 0;
		public static final int TXT_HELLO_CUSTOM_STYLE = 1;
		public static final int TXT_HOW_ARE_YOU = 2;
		public static final int TXT_CLICK_ME = 3;
	}

}
