/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.tabscreenexample;

public final class Res {

	public static final class id {
		public static final int layout_start = 4;
		public static final int BUTTON = 5;
		public static final int LABEL = 6;
		public static final int TAB_SCREEN_CONTENT_LABEL = 7;
	}

	public static final class layout {
		public static final int TAB_SUB_SCREEN = 1;
		public static final int NOT_SUPPORTED_LAYOUT = 2;
		public static final int SCREEN_WITH_BUTTON = 3;
	}

	public static final class string {
		public static final int TXT_NOT_SUPPORTED = 0;
	}

}
