/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.httpuploadexample;

public final class Res {

	public static final class id {
		public static final int UPLOAD_BUTTON = 4;
		public static final int UPLOAD_RESULT = 5;
	}

	public static final class layout {
		public static final int MAIN_SCREEN = 3;
	}

	public static final class string {
		public static final int HTTP_UPLOAD_EXAMPLE = 0;
		public static final int UPLOAD_IMAGE = 1;
		public static final int UPLOADING = 2;
	}

}
