/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.notificationexample;

public final class Res {

	public static final class id {
		public static final int layout_start = 19;
		public static final int buttonNotifyImmediate = 20;
		public static final int labelPayload = 21;
		public static final int labelPushServiceCurrentID = 22;
		public static final int buttonNotifyIn15Seconds = 23;
		public static final int labelPushServiceStatus = 24;
		public static final int buttonRegister = 25;
		public static final int labelMessageDesc = 26;
		public static final int buttonNotifyEvery30Minutes = 27;
		public static final int buttonCancelAll = 28;
	}

	public static final class image {
		public static final int NOTIF_ICON = 11;
		public static final int LAUNCH_IMG = 12;
		public static final int ACCESSORY_ICON = 13;
	}

	public static final class layout {
		public static final int LOCAL_NOTIFICATION_SCREEN = 14;
		public static final int LOCAL_NOTIFICATION_DETAILS_SCREEN = 15;
		public static final int PUSH_NOTIFICATION_SCREEN = 16;
		public static final int PUSH_MESSAGE_DETAILS_SCREEN = 17;
		public static final int NOT_SUPPORTED_LAYOUT = 18;
	}

	public static final class music {
		public static final int SOUND_NOTIF = 9;
		public static final int SOUND_NOTIF_IOS = 10;
	}

	public static final class string {
		public static final int register = 0;
		public static final int UNREGISTER = 1;
		public static final int NAME = 2;
		public static final int SEND = 3;
		public static final int ACTION = 4;
		public static final int PM_NEW_MESSAGE = 5;
		public static final int ARG1 = 6;
		public static final int ARG2 = 7;
		public static final int TXT_NOT_SUPPORTED = 8;
	}

}
