/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.animationexample;

public final class Res {

	public static final class id {
		public static final int door_top_image = 10;
		public static final int door_bottom_image = 11;
		public static final int fabric_bottom_image = 12;
		public static final int fabric_top_image = 13;
		public static final int bug_image = 14;
		public static final int layout_start = 15;
	}

	public static final class image {
		public static final int BUG = 2;
		public static final int PLATE_CHEESE = 3;
		public static final int DOOR_TOP = 4;
		public static final int DOOR_BOTTOM = 5;
		public static final int FABRIC_TOP = 6;
		public static final int FABRIC_BOTTOM = 7;
	}

	public static final class layout {
		public static final int ANIMATION_LAYOUT = 8;
		public static final int NOT_SUPPORTED_LAYOUT = 9;
	}

	public static final class string {
		public static final int TXT_NOT_SUPPORTED = 0;
		public static final int TXT_START = 1;
	}

}
