/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.cameraexample;

public final class Res {

	public static final class id {
		public static final int CAMERA_BUTTON = 3;
		public static final int MAINSCREEN_IMAGELABEL = 4;
	}

	public static final class layout {
		public static final int MAINSCREEN = 2;
	}

	public static final class string {
		public static final int MAINSCREEN_LABEL = 0;
		public static final int CAMERA_BUTTON_LABEL = 1;
	}

}
