/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.rssreader;

public final class Res {

	public static final class id {
		public static final int item_desc = 1;
		public static final int item_picture = 2;
		public static final int item_title = 3;
	}

	public static final class layout {
		public static final int feedItem = 0;
	}

}
