/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.example.sensor;

public final class Res {

	public static final class id {
		public static final int Y_LABEL = 31;
		public static final int ERROR_SENSOR_LABEL = 32;
		public static final int DESCRIPTION_LABEL = 33;
		public static final int ACCELEROMETER_LABEL = 34;
		public static final int GYROSCOPE_LABEL = 35;
		public static final int COMBO = 36;
		public static final int START_BUTTON = 37;
		public static final int Z_LABEL = 38;
		public static final int SPEED_LABEL = 39;
		public static final int X_LABEL = 40;
		public static final int LIST = 41;
		public static final int STOP_BUTTON = 42;
		public static final int MAGNETOMETER_LABEL = 43;
	}

	public static final class layout {
		public static final int NO_SENSOR = 28;
		public static final int MENU_SCREEN = 29;
		public static final int SENSOR_EXAMPLE_SCREEN = 30;
	}

	public static final class string {
		public static final int ACCELEROMETER = 0;
		public static final int GYROSCOPE = 1;
		public static final int MAGNETOMETER = 2;
		public static final int DESCRIPTION = 3;
		public static final int X = 4;
		public static final int Y = 5;
		public static final int Z = 6;
		public static final int X_ = 7;
		public static final int Y_ = 8;
		public static final int Z_ = 9;
		public static final int START = 10;
		public static final int STOP = 11;
		public static final int SPEED = 12;
		public static final int LOW = 13;
		public static final int NORMAL = 14;
		public static final int GAME = 15;
		public static final int FASTEST = 16;
		public static final int ERROR_SENSOR = 17;
		public static final int ERROR_ACCELEROMETER = 18;
		public static final int ERROR_GYROSCOPE = 19;
		public static final int ERROR_MAGNETOMETER = 20;
		public static final int DESCRIPTION_ACCELEROMETER = 21;
		public static final int DESCRIPTION_GYROSCOPE = 22;
		public static final int DESCRIPTION_MAGNETOMTER = 23;
		public static final int TITRE_MENU = 24;
		public static final int TITRE_ACCELEROMETER = 25;
		public static final int TITRE_GYROSCOPE = 26;
		public static final int TITRE_MAGNETOMETER = 27;
	}

}
