/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.slidemenuexample;

public final class Res {

	public static final class id {
		public static final int icon = 12;
		public static final int title = 13;
		public static final int main_img = 14;
		public static final int main_layout = 15;
		public static final int main_txt = 16;
		public static final int layout_start = 17;
	}

	public static final class image {
		public static final int ic_home = 5;
		public static final int ic_people = 6;
		public static final int ic_photos = 7;
		public static final int ic_about = 8;
	}

	public static final class layout {
		public static final int MAIN_SCREEN = 9;
		public static final int SLIDING_ITEM = 10;
		public static final int NOT_SUPPORTED_LAYOUT = 11;
	}

	public static final class string {
		public static final int HOME = 0;
		public static final int PHOTO = 1;
		public static final int ABOUT = 2;
		public static final int FIND_PEOPLE = 3;
		public static final int TXT_NOT_SUPPORTED = 4;
	}

}
