/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class provides IDs to access resources declared in the URS file.
 * It was automatically generated by NeoMAD and should not be modified by hand.
 */

package com.neomades.xmlpullparserexample;

public final class Res {

	public static final class id {
		public static final int PARSE_XML = 13;
		public static final int DISCUSSION_USER_NAME = 14;
		public static final int BUTTON_READ_XML = 15;
		public static final int DISCUSSION_LAYOUT = 16;
		public static final int DISCUSSION_TEXT = 17;
		public static final int PARSE_TITLE = 18;
		public static final int XML_FILE_ID = 19;
	}

	public static final class layout {
		public static final int MAIN_SCREEN = 9;
		public static final int DISCUSSION_ITEM = 10;
		public static final int READING_SCREEN = 11;
		public static final int DISCUSSION_SCREEN = 12;
	}

	public static final class raw {
		public static final int XML_FILE = 8;
	}

	public static final class string {
		public static final int READ_XML = 0;
		public static final int PARSE_STRING_TITLE = 1;
		public static final int PARSE = 2;
		public static final int READING_TITLE = 3;
		public static final int DISCUSSION_TITLE = 4;
		public static final int MAIN_TITLE = 5;
		public static final int SAY = 6;
		public static final int ENCODING_ERROR = 7;
	}

}
